config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items do
    member do
      delete :delete
    end
  end
  resources :carts
  root 'store#index', as: 'store_index'

  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MSI Online Tech Shop</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      MSI Online Tech Shop
      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <div id ="date_time">
          Date: <%= Time.now %> <br/>
          <%# if session[:counter] >= 5 %>
<!--            Session : <%#= (session[:counter]<5)?nil:session[:counter] %>-->
          <%# end %>
        </div>

        <div id="cart">
          <%if @cart %>
            <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
               <%= render @cart %>
            <%end %>
          <%end %>
        </div>

        <ul>
          <li><%= link_to "Home" , products_path %></li>
          <li><%= link_to "Sort with Price" , store_index_path %></li>
          <li><a href="https://www.nascenia.com/">News</a></li>
          <li><a href="https://www.facebook.com/sabik.irbaz">Contacts</a></li>
        </ul>
        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
            <% end %>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>